version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    volumes:
      - ./backups/:/app/backups
    env_file:
      - docker.env
    command: ["python", "main.py"]
    depends_on:
      - db