name: Deploy to remote server
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USERNAME_SERVER }}
          key: ${{ secrets.KEY_SERVER }}
          script: |
            cd ~/projects/bot_financial_accounting
            git pull origin main
            systemctl restart bot_financial_accounting.service
